#pragma once

#include "../engine/types.h"



namespace VKEngine {
  typedef uint32_t Key;

  enum KeyCodes : Key
  {
#ifdef PLATFORM_WINDOWS

    // From WinUser.h
    MouseLeftButton    = VK_LBUTTON,
    MouseRightButton   = VK_RBUTTON,
    MouseMiddleButton  = VK_MBUTTON,

    Backspace     = VK_BACK,
    Tab           = VK_TAB,
    Clear         = VK_CLEAR,
    Enter         = VK_RETURN,
    Pause         = VK_PAUSE,
    CapsLock      = VK_CAPITAL,
    Escape        = VK_ESCAPE,
    Space         = VK_SPACE,
    PageUp        = VK_PRIOR,
    PageDown      = VK_NEXT,
    End           = VK_END,
    Home          = VK_HOME,
    Left          = VK_LEFT,
    Up            = VK_UP,
    Right         = VK_RIGHT,
    Down          = VK_DOWN,
    PrintScreen   = VK_SNAPSHOT,
    Insert        = VK_INSERT,
    Delete        = VK_DELETE,

    Key0 = 48,
    Key1 = 49,
    Key2 = 50,
    Key3 = 51,
    Key4 = 52,
    Key5 = 53,
    Key6 = 54,
    Key7 = 55,
    Key8 = 56,
    Key9 = 57,

    A = 65,
    B = 66,
    C = 67,
    D = 68,
    E = 69,
    F = 70,
    G = 71,
    H = 72,
    I = 73,
    J = 74,
    K = 75,
    L = 76,
    M = 77,
    N = 78,
    O = 79,
    P = 80,
    Q = 81,
    R = 82,
    S = 83,
    T = 84,
    U = 85,
    V = 86,
    W = 87,
    X = 88,
    Y = 89,
    Z = 90,

    Numpad0     = VK_NUMPAD0,
    Numpad1     = VK_NUMPAD1,
    Numpad2     = VK_NUMPAD2,
    Numpad3     = VK_NUMPAD3,
    Numpad4     = VK_NUMPAD4,
    Numpad5     = VK_NUMPAD5,
    Numpad6     = VK_NUMPAD6,
    Numpad7     = VK_NUMPAD7,
    Numpad8     = VK_NUMPAD8,
    Numpad9     = VK_NUMPAD9,
    Multiply    = VK_MULTIPLY,
    Add         = VK_ADD,
    Separator   = VK_SEPARATOR,
    Substract   = VK_SUBTRACT,
    Decimal     = VK_DECIMAL,
    Divide      = VK_DIVIDE,

    F1   = VK_F1,
    F2   = VK_F2,
    F3   = VK_F3,
    F4   = VK_F4,
    F5   = VK_F5,
    F6   = VK_F6,
    F7   = VK_F7,
    F8   = VK_F8,
    F9   = VK_F9,
    F10  = VK_F10,
    F11  = VK_F11,
    F12  = VK_F12,
    F13  = VK_F13,
    F14  = VK_F14,
    F15  = VK_F15,
    F16  = VK_F16,
    F17  = VK_F17,
    F18  = VK_F18,
    F19  = VK_F19,
    F20  = VK_F20,
    F21  = VK_F21,
    F22  = VK_F22,
    F23  = VK_F23,
    F24  = VK_F24,

    LeftShift     = VK_LSHIFT,
    RightShift    = VK_RSHIFT,
    LeftControl   = VK_LCONTROL,
    RightControl  = VK_RCONTROL,
    LeftAlt       = VK_LMENU,
    RightAlt      = VK_RMENU,

#elif defined(USE_SDL)
    
    // From SDL_keycode.h
    MouseLeftButton    = SDL_BUTTON_LEFT,
    MouseRightButton   = SDL_BUTTON_RIGHT,
    MouseMiddleButton  = SDL_BUTTON_MIDDLE,

    Backspace     = SDLK_BACKSPACE,
    Tab           = SDLK_TAB,
    Clear         = SDLK_CLEAR,
    Enter         = SDLK_RETURN,
    Pause         = SDLK_PAUSE,
    CapsLock      = SDLK_CAPSLOCK,
    Escape        = SDLK_ESCAPE,
    Space         = SDLK_SPACE,
    PageUp        = SDLK_PAGEUP,
    PageDown      = SDLK_PAGEDOWN,
    End           = SDLK_END,
    Home          = SDLK_HOME,
    Left          = SDLK_LEFT,
    Up            = SDLK_UP,
    Right         = SDLK_RIGHT,
    Down          = SDLK_DOWN,
    PrintScreen   = SDLK_PRINTSCREEN,
    Insert        = SDLK_INSERT,
    Delete        = SDLK_DELETE,

    Key0 = SDLK_0,
    Key1 = SDLK_1,
    Key2 = SDLK_2,
    Key3 = SDLK_3,
    Key4 = SDLK_4,
    Key5 = SDLK_5,
    Key6 = SDLK_6,
    Key7 = SDLK_7,
    Key8 = SDLK_8,
    Key9 = SDLK_9,

    A = SDLK_a,
    B = SDLK_b,
    C = SDLK_c,
    D = SDLK_d,
    E = SDLK_e,
    F = SDLK_f,
    G = SDLK_g,
    H = SDLK_h,
    I = SDLK_i,
    J = SDLK_j,
    K = SDLK_k,
    L = SDLK_l,
    M = SDLK_m,
    N = SDLK_n,
    O = SDLK_o,
    P = SDLK_p,
    Q = SDLK_q,
    R = SDLK_r,
    S = SDLK_s,
    T = SDLK_t,
    U = SDLK_u,
    V = SDLK_v,
    W = SDLK_w,
    X = SDLK_x,
    Y = SDLK_y,
    Z = SDLK_z,

    Numpad0     = SDLK_KP_0,
    Numpad1     = SDLK_KP_1,
    Numpad2     = SDLK_KP_2,
    Numpad3     = SDLK_KP_3,
    Numpad4     = SDLK_KP_4,
    Numpad5     = SDLK_KP_5,
    Numpad6     = SDLK_KP_6,
    Numpad7     = SDLK_KP_7,
    Numpad8     = SDLK_KP_8,
    Numpad9     = SDLK_KP_9,
    Multiply    = SDLK_KP_MULTIPLY,
    Add         = SDLK_KP_PLUS,
    Separator   = SDLK_KP_COMMA,
    Substract   = SDLK_KP_MINUS,
    Decimal     = SDLK_KP_DECIMAL,
    Divide      = SDLK_KP_DIVIDE,

    F1   = SDLK_F1,
    F2   = SDLK_F2,
    F3   = SDLK_F3,
    F4   = SDLK_F4,
    F5   = SDLK_F5,
    F6   = SDLK_F6,
    F7   = SDLK_F7,
    F8   = SDLK_F8,
    F9   = SDLK_F9,
    F10  = SDLK_F10,
    F11  = SDLK_F11,
    F12  = SDLK_F12,
    F13  = SDLK_F13,
    F14  = SDLK_F14,
    F15  = SDLK_F15,
    F16  = SDLK_F16,
    F17  = SDLK_F17,
    F18  = SDLK_F18,
    F19  = SDLK_F19,
    F20  = SDLK_F20,
    F21  = SDLK_F21,
    F22  = SDLK_F22,
    F23  = SDLK_F23,
    F24  = SDLK_F24,

    LeftShift     = SDLK_LSHIFT,
    RightShift    = SDLK_RSHIFT,
    LeftControl   = SDLK_LCTRL,
    RightControl  = SDLK_RCTRL,
    LeftAlt       = SDLK_LALT,
    RightAlt      = SDLK_RALT,
#endif
  };
}

